package com.kedacom.ezSafe.common.domain;

import java.io.Serializable;

public class BQjXzqy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZMC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZJB
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private Short xzjb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZQH
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZNBBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xznbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZJC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xzjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XSSX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xssx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.SFKY
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String sfky;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.QYPY
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String qypy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.YLZD1
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String ylzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.YLZD2
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String ylzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.YLZD3
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String ylzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.ZFJG
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String zfjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XMIN
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.YMIN
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String ymin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XMAX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.YMAX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String ymax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.XZFBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String xzfbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XZQY.MCJC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    private String mcjc;

    private String xcenter;

    private String ycenter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZBM
     *
     * @return the value of B_QJ_XZQY.XZBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXzbm() {
        return xzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZBM
     *
     * @param xzbm the value for B_QJ_XZQY.XZBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXzbm(String xzbm) {
        this.xzbm = xzbm == null ? null : xzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZMC
     *
     * @return the value of B_QJ_XZQY.XZMC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXzmc() {
        return xzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZMC
     *
     * @param xzmc the value for B_QJ_XZQY.XZMC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXzmc(String xzmc) {
        this.xzmc = xzmc == null ? null : xzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZJB
     *
     * @return the value of B_QJ_XZQY.XZJB
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public Short getXzjb() {
        return xzjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZJB
     *
     * @param xzjb the value for B_QJ_XZQY.XZJB
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXzjb(Short xzjb) {
        this.xzjb = xzjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZQH
     *
     * @return the value of B_QJ_XZQY.XZQH
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZQH
     *
     * @param xzqh the value for B_QJ_XZQY.XZQH
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZNBBM
     *
     * @return the value of B_QJ_XZQY.XZNBBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXznbbm() {
        return xznbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZNBBM
     *
     * @param xznbbm the value for B_QJ_XZQY.XZNBBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXznbbm(String xznbbm) {
        this.xznbbm = xznbbm == null ? null : xznbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZJC
     *
     * @return the value of B_QJ_XZQY.XZJC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXzjc() {
        return xzjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZJC
     *
     * @param xzjc the value for B_QJ_XZQY.XZJC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXzjc(String xzjc) {
        this.xzjc = xzjc == null ? null : xzjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XSSX
     *
     * @return the value of B_QJ_XZQY.XSSX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXssx() {
        return xssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XSSX
     *
     * @param xssx the value for B_QJ_XZQY.XSSX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXssx(String xssx) {
        this.xssx = xssx == null ? null : xssx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.SFKY
     *
     * @return the value of B_QJ_XZQY.SFKY
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getSfky() {
        return sfky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.SFKY
     *
     * @param sfky the value for B_QJ_XZQY.SFKY
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setSfky(String sfky) {
        this.sfky = sfky == null ? null : sfky.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.QYPY
     *
     * @return the value of B_QJ_XZQY.QYPY
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getQypy() {
        return qypy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.QYPY
     *
     * @param qypy the value for B_QJ_XZQY.QYPY
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setQypy(String qypy) {
        this.qypy = qypy == null ? null : qypy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.YLZD1
     *
     * @return the value of B_QJ_XZQY.YLZD1
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getYlzd1() {
        return ylzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.YLZD1
     *
     * @param ylzd1 the value for B_QJ_XZQY.YLZD1
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setYlzd1(String ylzd1) {
        this.ylzd1 = ylzd1 == null ? null : ylzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.YLZD2
     *
     * @return the value of B_QJ_XZQY.YLZD2
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getYlzd2() {
        return ylzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.YLZD2
     *
     * @param ylzd2 the value for B_QJ_XZQY.YLZD2
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setYlzd2(String ylzd2) {
        this.ylzd2 = ylzd2 == null ? null : ylzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.YLZD3
     *
     * @return the value of B_QJ_XZQY.YLZD3
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getYlzd3() {
        return ylzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.YLZD3
     *
     * @param ylzd3 the value for B_QJ_XZQY.YLZD3
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setYlzd3(String ylzd3) {
        this.ylzd3 = ylzd3 == null ? null : ylzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.ZFJG
     *
     * @return the value of B_QJ_XZQY.ZFJG
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getZfjg() {
        return zfjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.ZFJG
     *
     * @param zfjg the value for B_QJ_XZQY.ZFJG
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setZfjg(String zfjg) {
        this.zfjg = zfjg == null ? null : zfjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XMIN
     *
     * @return the value of B_QJ_XZQY.XMIN
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXmin() {
        return xmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XMIN
     *
     * @param xmin the value for B_QJ_XZQY.XMIN
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXmin(String xmin) {
        this.xmin = xmin == null ? null : xmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.YMIN
     *
     * @return the value of B_QJ_XZQY.YMIN
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getYmin() {
        return ymin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.YMIN
     *
     * @param ymin the value for B_QJ_XZQY.YMIN
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setYmin(String ymin) {
        this.ymin = ymin == null ? null : ymin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XMAX
     *
     * @return the value of B_QJ_XZQY.XMAX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXmax() {
        return xmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XMAX
     *
     * @param xmax the value for B_QJ_XZQY.XMAX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXmax(String xmax) {
        this.xmax = xmax == null ? null : xmax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.YMAX
     *
     * @return the value of B_QJ_XZQY.YMAX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getYmax() {
        return ymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.YMAX
     *
     * @param ymax the value for B_QJ_XZQY.YMAX
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setYmax(String ymax) {
        this.ymax = ymax == null ? null : ymax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.XZFBM
     *
     * @return the value of B_QJ_XZQY.XZFBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getXzfbm() {
        return xzfbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.XZFBM
     *
     * @param xzfbm the value for B_QJ_XZQY.XZFBM
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setXzfbm(String xzfbm) {
        this.xzfbm = xzfbm == null ? null : xzfbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XZQY.MCJC
     *
     * @return the value of B_QJ_XZQY.MCJC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public String getMcjc() {
        return mcjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XZQY.MCJC
     *
     * @param mcjc the value for B_QJ_XZQY.MCJC
     *
     * @mbggenerated Sat Dec 02 10:32:23 CST 2017
     */
    public void setMcjc(String mcjc) {
        this.mcjc = mcjc == null ? null : mcjc.trim();
    }

    public String getXcenter() {
        return xcenter;
    }

    public void setXcenter(String xcenter) {
        this.xcenter = xcenter;
    }

    public String getYcenter() {
        return ycenter;
    }

    public void setYcenter(String ycenter) {
        this.ycenter = ycenter;
    }
}