package com.kedacom.ezSafe.common.domain;

import java.io.Serializable;

public class BQjXtpz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XTPZ.XH
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    private Long xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XTPZ.BLM
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    private String blm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XTPZ.BLZWM
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    private String blzwm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_XTPZ.PZZ
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    private String pzz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XTPZ.XH
     *
     * @return the value of B_QJ_XTPZ.XH
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public Long getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XTPZ.XH
     *
     * @param xh the value for B_QJ_XTPZ.XH
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public void setXh(Long xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XTPZ.BLM
     *
     * @return the value of B_QJ_XTPZ.BLM
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public String getBlm() {
        return blm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XTPZ.BLM
     *
     * @param blm the value for B_QJ_XTPZ.BLM
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public void setBlm(String blm) {
        this.blm = blm == null ? null : blm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XTPZ.BLZWM
     *
     * @return the value of B_QJ_XTPZ.BLZWM
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public String getBlzwm() {
        return blzwm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XTPZ.BLZWM
     *
     * @param blzwm the value for B_QJ_XTPZ.BLZWM
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public void setBlzwm(String blzwm) {
        this.blzwm = blzwm == null ? null : blzwm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_XTPZ.PZZ
     *
     * @return the value of B_QJ_XTPZ.PZZ
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public String getPzz() {
        return pzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_XTPZ.PZZ
     *
     * @param pzz the value for B_QJ_XTPZ.PZZ
     *
     * @mbggenerated Tue Sep 08 13:28:43 CST 2015
     */
    public void setPzz(String pzz) {
        this.pzz = pzz == null ? null : pzz.trim();
    }
}