package com.kedacom.ezSafe.common.domain;

import java.io.Serializable;

public class BQjZdx extends BQjZdxKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDMC
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDJB
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdjb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDJC
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDMS
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDPY
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdpy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDSX
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.NBBM
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String nbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.FJBH
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String fjbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.SFXS
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String sfxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.SFMR
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String sfmr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.YLZD1
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String ylzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.YLZD2
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String ylzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.YLZD3
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String ylzd3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDMC
     *
     * @return the value of B_QJ_ZDX.ZDMC
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdmc() {
        return zdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDMC
     *
     * @param zdmc the value for B_QJ_ZDX.ZDMC
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdmc(String zdmc) {
        this.zdmc = zdmc == null ? null : zdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDJB
     *
     * @return the value of B_QJ_ZDX.ZDJB
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdjb() {
        return zdjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDJB
     *
     * @param zdjb the value for B_QJ_ZDX.ZDJB
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdjb(String zdjb) {
        this.zdjb = zdjb == null ? null : zdjb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDJC
     *
     * @return the value of B_QJ_ZDX.ZDJC
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdjc() {
        return zdjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDJC
     *
     * @param zdjc the value for B_QJ_ZDX.ZDJC
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdjc(String zdjc) {
        this.zdjc = zdjc == null ? null : zdjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDMS
     *
     * @return the value of B_QJ_ZDX.ZDMS
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdms() {
        return zdms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDMS
     *
     * @param zdms the value for B_QJ_ZDX.ZDMS
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdms(String zdms) {
        this.zdms = zdms == null ? null : zdms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDPY
     *
     * @return the value of B_QJ_ZDX.ZDPY
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdpy() {
        return zdpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDPY
     *
     * @param zdpy the value for B_QJ_ZDX.ZDPY
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdpy(String zdpy) {
        this.zdpy = zdpy == null ? null : zdpy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDSX
     *
     * @return the value of B_QJ_ZDX.ZDSX
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdsx() {
        return zdsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDSX
     *
     * @param zdsx the value for B_QJ_ZDX.ZDSX
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdsx(String zdsx) {
        this.zdsx = zdsx == null ? null : zdsx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.NBBM
     *
     * @return the value of B_QJ_ZDX.NBBM
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getNbbm() {
        return nbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.NBBM
     *
     * @param nbbm the value for B_QJ_ZDX.NBBM
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setNbbm(String nbbm) {
        this.nbbm = nbbm == null ? null : nbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.FJBH
     *
     * @return the value of B_QJ_ZDX.FJBH
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getFjbh() {
        return fjbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.FJBH
     *
     * @param fjbh the value for B_QJ_ZDX.FJBH
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setFjbh(String fjbh) {
        this.fjbh = fjbh == null ? null : fjbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.SFXS
     *
     * @return the value of B_QJ_ZDX.SFXS
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getSfxs() {
        return sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.SFXS
     *
     * @param sfxs the value for B_QJ_ZDX.SFXS
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setSfxs(String sfxs) {
        this.sfxs = sfxs == null ? null : sfxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.SFMR
     *
     * @return the value of B_QJ_ZDX.SFMR
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getSfmr() {
        return sfmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.SFMR
     *
     * @param sfmr the value for B_QJ_ZDX.SFMR
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setSfmr(String sfmr) {
        this.sfmr = sfmr == null ? null : sfmr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.YLZD1
     *
     * @return the value of B_QJ_ZDX.YLZD1
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getYlzd1() {
        return ylzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.YLZD1
     *
     * @param ylzd1 the value for B_QJ_ZDX.YLZD1
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setYlzd1(String ylzd1) {
        this.ylzd1 = ylzd1 == null ? null : ylzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.YLZD2
     *
     * @return the value of B_QJ_ZDX.YLZD2
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getYlzd2() {
        return ylzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.YLZD2
     *
     * @param ylzd2 the value for B_QJ_ZDX.YLZD2
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setYlzd2(String ylzd2) {
        this.ylzd2 = ylzd2 == null ? null : ylzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.YLZD3
     *
     * @return the value of B_QJ_ZDX.YLZD3
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getYlzd3() {
        return ylzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.YLZD3
     *
     * @param ylzd3 the value for B_QJ_ZDX.YLZD3
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setYlzd3(String ylzd3) {
        this.ylzd3 = ylzd3 == null ? null : ylzd3.trim();
    }
}