package com.kedacom.ezSafe.common.domain;

public class BQjZdxKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDBH
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_QJ_ZDX.ZDLX
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    private String zdlx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDBH
     *
     * @return the value of B_QJ_ZDX.ZDBH
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdbh() {
        return zdbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDBH
     *
     * @param zdbh the value for B_QJ_ZDX.ZDBH
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdbh(String zdbh) {
        this.zdbh = zdbh == null ? null : zdbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_QJ_ZDX.ZDLX
     *
     * @return the value of B_QJ_ZDX.ZDLX
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public String getZdlx() {
        return zdlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_QJ_ZDX.ZDLX
     *
     * @param zdlx the value for B_QJ_ZDX.ZDLX
     *
     * @mbggenerated Wed Sep 27 11:02:47 CST 2017
     */
    public void setZdlx(String zdlx) {
        this.zdlx = zdlx == null ? null : zdlx.trim();
    }
}