package com.kedacom.ezSafe.common.domain;

import java.io.Serializable;

/**
 * 单位表B_RS_DW
 */
public class Unit implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.XH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private Long xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWBH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWMC
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWDZ
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.LXDH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.LXR
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWJB
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwjb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.LSGX
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String lsgx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWNBBM
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwnbbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWMS
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.DWSX
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String dwsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.SFXQ
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private Long sfxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.YLZD1
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String ylzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.YLZD2
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String ylzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_DW.YLZD3
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String ylzd3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.XH
     *
     * @return the value of B_RS_DW.XH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    private String ssxq;   //所属辖区

    public Long getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.XH
     *
     * @param xh the value for B_RS_DW.XH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setXh(Long xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWBH
     *
     * @return the value of B_RS_DW.DWBH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwbh() {
        return dwbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWBH
     *
     * @param dwbh the value for B_RS_DW.DWBH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwbh(String dwbh) {
        this.dwbh = dwbh == null ? null : dwbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWMC
     *
     * @return the value of B_RS_DW.DWMC
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwmc() {
        return dwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWMC
     *
     * @param dwmc the value for B_RS_DW.DWMC
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwmc(String dwmc) {
        this.dwmc = dwmc == null ? null : dwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWDZ
     *
     * @return the value of B_RS_DW.DWDZ
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwdz() {
        return dwdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWDZ
     *
     * @param dwdz the value for B_RS_DW.DWDZ
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwdz(String dwdz) {
        this.dwdz = dwdz == null ? null : dwdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.LXDH
     *
     * @return the value of B_RS_DW.LXDH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.LXDH
     *
     * @param lxdh the value for B_RS_DW.LXDH
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.LXR
     *
     * @return the value of B_RS_DW.LXR
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.LXR
     *
     * @param lxr the value for B_RS_DW.LXR
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWJB
     *
     * @return the value of B_RS_DW.DWJB
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwjb() {
        return dwjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWJB
     *
     * @param dwjb the value for B_RS_DW.DWJB
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwjb(String dwjb) {
        this.dwjb = dwjb == null ? null : dwjb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.LSGX
     *
     * @return the value of B_RS_DW.LSGX
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getLsgx() {
        return lsgx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.LSGX
     *
     * @param lsgx the value for B_RS_DW.LSGX
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setLsgx(String lsgx) {
        this.lsgx = lsgx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWNBBM
     *
     * @return the value of B_RS_DW.DWNBBM
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwnbbm() {
        return dwnbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWNBBM
     *
     * @param dwnbbm the value for B_RS_DW.DWNBBM
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwnbbm(String dwnbbm) {
        this.dwnbbm = dwnbbm == null ? null : dwnbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWMS
     *
     * @return the value of B_RS_DW.DWMS
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwms() {
        return dwms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWSX
     *
     * @param dwsx the value for B_RS_DW.DWSX
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwsx(String dwsx) {
        this.dwsx = dwsx == null ? null : dwsx.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.DWSX
     *
     * @return the value of B_RS_DW.DWSX
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getDwsx() {
        return dwsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.SFXQ
     *
     * @param sfxq the value for B_RS_DW.SFXQ
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setSfxq(Long sfxq) {
        this.sfxq = sfxq == null ? 0 : sfxq;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.SFXQ
     *
     * @return the value of B_RS_DW.SFXQ
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public Long getSfxq() {
        return sfxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.DWMS
     *
     * @param dwms the value for B_RS_DW.DWMS
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setDwms(String dwms) {
        this.dwms = dwms == null ? null : dwms.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.YLZD1
     *
     * @return the value of B_RS_DW.YLZD1
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getYlzd1() {
        return ylzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.YLZD1
     *
     * @param ylzd1 the value for B_RS_DW.YLZD1
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setYlzd1(String ylzd1) {
        this.ylzd1 = ylzd1 == null ? null : ylzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.YLZD2
     *
     * @return the value of B_RS_DW.YLZD2
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getYlzd2() {
        return ylzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.YLZD2
     *
     * @param ylzd2 the value for B_RS_DW.YLZD2
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setYlzd2(String ylzd2) {
        this.ylzd2 = ylzd2 == null ? null : ylzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_DW.YLZD3
     *
     * @return the value of B_RS_DW.YLZD3
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public String getYlzd3() {
        return ylzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_DW.YLZD3
     *
     * @param ylzd3 the value for B_RS_DW.YLZD3
     *
     * @mbggenerated Wed Mar 11 18:29:02 CST 2015
     */
    public void setYlzd3(String ylzd3) {
        this.ylzd3 = ylzd3 == null ? null : ylzd3.trim();
    }

    public String getSsxq() {
        return ssxq;
    }

    public void setSsxq(String ssxq) {
        this.ssxq = ssxq;
    }
}