package com.kedacom.ezSafe.common.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.XH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private Long xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.DLM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String dlm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.JH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String jh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.JYXM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String jyxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.JYLB
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String jylb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.LSDW
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String lsdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.ZW
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.SFZH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.LXDH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.SJHM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String sjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YHZT
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String yhzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YHZCSJ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String yhzcsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YHYXQ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String yhyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.IPJYQSDZ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String ipjyqsdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.IPJYJSDZ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String ipjyjsdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.DLSY
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String dlsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YHMS
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String yhms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YLZD1
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String ylzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YLDZ2
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String yldz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_RS_RY.YLZD3
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    private String ylzd3;

    private String dlmm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.XH
     *
     * @return the value of B_RS_RY.XH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public Long getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.XH
     *
     * @param xh the value for B_RS_RY.XH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setXh(Long xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.DLM
     *
     * @return the value of B_RS_RY.DLM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getDlm() {
        return dlm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.DLM
     *
     * @param dlm the value for B_RS_RY.DLM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setDlm(String dlm) {
        this.dlm = dlm == null ? null : dlm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.JH
     *
     * @return the value of B_RS_RY.JH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getJh() {
        return jh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.JH
     *
     * @param jh the value for B_RS_RY.JH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setJh(String jh) {
        this.jh = jh == null ? null : jh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.JYXM
     *
     * @return the value of B_RS_RY.JYXM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getJyxm() {
        return jyxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.JYXM
     *
     * @param jyxm the value for B_RS_RY.JYXM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setJyxm(String jyxm) {
        this.jyxm = jyxm == null ? null : jyxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.JYLB
     *
     * @return the value of B_RS_RY.JYLB
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getJylb() {
        return jylb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.JYLB
     *
     * @param jylb the value for B_RS_RY.JYLB
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setJylb(String jylb) {
        this.jylb = jylb == null ? null : jylb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.LSDW
     *
     * @return the value of B_RS_RY.LSDW
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getLsdw() {
        return lsdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.LSDW
     *
     * @param lsdw the value for B_RS_RY.LSDW
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setLsdw(String lsdw) {
        this.lsdw = lsdw == null ? null : lsdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.ZW
     *
     * @return the value of B_RS_RY.ZW
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.ZW
     *
     * @param zw the value for B_RS_RY.ZW
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setZw(String zw) {
        this.zw = zw == null ? null : zw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.SFZH
     *
     * @return the value of B_RS_RY.SFZH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.SFZH
     *
     * @param sfzh the value for B_RS_RY.SFZH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.LXDH
     *
     * @return the value of B_RS_RY.LXDH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.LXDH
     *
     * @param lxdh the value for B_RS_RY.LXDH
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.SJHM
     *
     * @return the value of B_RS_RY.SJHM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getSjhm() {
        return sjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.SJHM
     *
     * @param sjhm the value for B_RS_RY.SJHM
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setSjhm(String sjhm) {
        this.sjhm = sjhm == null ? null : sjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YHZT
     *
     * @return the value of B_RS_RY.YHZT
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYhzt() {
        return yhzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YHZT
     *
     * @param yhzt the value for B_RS_RY.YHZT
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYhzt(String yhzt) {
        this.yhzt = yhzt == null ? null : yhzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YHZCSJ
     *
     * @return the value of B_RS_RY.YHZCSJ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYhzcsj() {
        return yhzcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YHZCSJ
     *
     * @param yhzcsj the value for B_RS_RY.YHZCSJ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYhzcsj(String yhzcsj) {
        this.yhzcsj = yhzcsj == null ? null : yhzcsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YHYXQ
     *
     * @return the value of B_RS_RY.YHYXQ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYhyxq() {
        return yhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YHYXQ
     *
     * @param yhyxq the value for B_RS_RY.YHYXQ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYhyxq(String yhyxq) {
        this.yhyxq = yhyxq == null ? null : yhyxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.IPJYQSDZ
     *
     * @return the value of B_RS_RY.IPJYQSDZ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getIpjyqsdz() {
        return ipjyqsdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.IPJYQSDZ
     *
     * @param ipjyqsdz the value for B_RS_RY.IPJYQSDZ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setIpjyqsdz(String ipjyqsdz) {
        this.ipjyqsdz = ipjyqsdz == null ? null : ipjyqsdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.IPJYJSDZ
     *
     * @return the value of B_RS_RY.IPJYJSDZ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getIpjyjsdz() {
        return ipjyjsdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.IPJYJSDZ
     *
     * @param ipjyjsdz the value for B_RS_RY.IPJYJSDZ
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setIpjyjsdz(String ipjyjsdz) {
        this.ipjyjsdz = ipjyjsdz == null ? null : ipjyjsdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.DLSY
     *
     * @return the value of B_RS_RY.DLSY
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getDlsy() {
        return dlsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.DLSY
     *
     * @param dlsy the value for B_RS_RY.DLSY
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setDlsy(String dlsy) {
        this.dlsy = dlsy == null ? null : dlsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YHMS
     *
     * @return the value of B_RS_RY.YHMS
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYhms() {
        return yhms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YHMS
     *
     * @param yhms the value for B_RS_RY.YHMS
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYhms(String yhms) {
        this.yhms = yhms == null ? null : yhms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YLZD1
     *
     * @return the value of B_RS_RY.YLZD1
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYlzd1() {
        return ylzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YLZD1
     *
     * @param ylzd1 the value for B_RS_RY.YLZD1
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYlzd1(String ylzd1) {
        this.ylzd1 = ylzd1 == null ? null : ylzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YLDZ2
     *
     * @return the value of B_RS_RY.YLDZ2
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYldz2() {
        return yldz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YLDZ2
     *
     * @param yldz2 the value for B_RS_RY.YLDZ2
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYldz2(String yldz2) {
        this.yldz2 = yldz2 == null ? null : yldz2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_RS_RY.YLZD3
     *
     * @return the value of B_RS_RY.YLZD3
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public String getYlzd3() {
        return ylzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_RS_RY.YLZD3
     *
     * @param ylzd3 the value for B_RS_RY.YLZD3
     *
     * @mbggenerated Sat Mar 21 13:43:28 CST 2015
     */
    public void setYlzd3(String ylzd3) {
        this.ylzd3 = ylzd3 == null ? null : ylzd3.trim();
    }

    public String getDlmm() {
        return dlmm;
    }

    public void setDlmm(String dlmm) {
        this.dlmm = dlmm;
    }
}